### ISSUE TITLE
jenkins pack fails to run chown tasks on systems to blacklist root user

### ISSUE THREAD

**Issue by attachmentgenie** [hashicorp/nomad-pack-community-registry#79]
the jenkins pack tries to run the chown task as root, which is a user that is on the default deny list. This should be documented or reworked imho.

**Comment by jrasell** [comment]
@attachmentgenie I completely agree and had not noticed it is using the exec driver. Ideally we would use Docker as a standard.

**Comment by attachmentgenie** [comment]
@jrasell PR inbound ;-)

**Comment by jrasell** [comment]
:nomad-chef-kiss:

**Comment by attachmentgenie** [comment]
the chown task was rewritten and accepted in #80
